// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1718791340);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1718791312);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1718791370);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1718791310);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 116);
user_pref("browser.newtabpage.activity-stream.impressionId", "{5fe41e07-5ec4-43f9-957e-9e691719ce3f}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.policies.runOncePerModification.displayBookmarksToolbar", "false");
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1718791311);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1718791331473");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1718793129473");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1718791317633");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1718812917633");
user_pref("browser.search.region", "IN");
user_pref("browser.startup.homepage_override.buildID", "20220105212146");
user_pref("browser.startup.homepage_override.mstone", "91.5.0");
user_pref("browser.startup.lastColdStartupCheck", 1718791311);
user_pref("browser.toolbars.bookmarks.visibility", "always");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("distribution.Kali.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "91.5.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.disable-heuristics", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "IN");
user_pref("dom.push.userAgentID", "3302cd4622d04cbfb8b5ec0ec9b8b3c0");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20220105212146");
user_pref("extensions.lastAppVersion", "91.5.0");
user_pref("extensions.lastPlatformVersion", "91.5.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"b3261230-e077-413e-802a-0b89891ce0c8\",\"formautofill@mozilla.org\":\"4a962f10-bbfa-4ad8-bd2a-175256918942\",\"pictureinpicture@mozilla.org\":\"91269d09-a6f0-4b38-8e7f-fd26a5c101ca\",\"proxy-failover@mozilla.com\":\"40624710-c307-40ba-9876-f8015aa1081c\",\"screenshots@mozilla.org\":\"fe53ad7a-1299-4c53-afab-94f250632e53\",\"webcompat-reporter@mozilla.org\":\"807595a3-5475-4606-94e1-06b6aa80dd8f\",\"webcompat@mozilla.org\":\"ee2d57c4-ec63-4ec2-a1fc-02bc6d611367\",\"default-theme@mozilla.org\":\"9fd74d7d-827e-4620-8e87-4fab83ed782d\",\"google@search.mozilla.org\":\"d0f53d55-8422-4785-95c5-356b2f9114f4\",\"wikipedia@search.mozilla.org\":\"ccfa1385-fd5a-4cbc-b30a-9bcf919068eb\",\"bing@search.mozilla.org\":\"b752a7b4-7024-4d2c-96d6-1db3182fe334\",\"ddg@search.mozilla.org\":\"6238f23e-eafc-4586-b647-661c062d3bfd\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1718791311);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("network.trr.uri", "https://mozilla.cloudflare-dns.com/dns-query");
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "5ac1d99b-995a-4365-94a3-8049ffd1daf0");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("toolkit.startup.last_success", 1718791309);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20220105212146");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
